# Generated by Django 4.0.4 on 2022-05-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_planta', models.CharField(max_length=80, verbose_name='tipo de planta')),
            ],
        ),
    ]
