# Generated by Django 4.0.4 on 2022-05-09 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crecimientoPlanta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.CharField(max_length=80)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crecimientoPlanta.tipoplanta')),
            ],
        ),
    ]
