# Generated by Django 4.0.4 on 2022-05-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crecimientoPlanta', '0002_plantas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantas',
            options={'verbose_name_plural': 'Plantas'},
        ),
        migrations.AlterModelOptions(
            name='tipoplanta',
            options={'verbose_name_plural': 'Tipo de plantas'},
        ),
        migrations.AlterField(
            model_name='tipoplanta',
            name='tipo_planta',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crecimientoPlanta.plantas')),
            ],
            options={
                'verbose_name_plural': 'Monitoreo',
            },
        ),
    ]
