# Generated by Django 4.0.4 on 2022-05-09 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crecimientoPlanta', '0003_alter_plantas_options_alter_tipoplanta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreo',
            name='altura',
            field=models.CharField(blank=b'I01\n', max_length=80),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
