# Generated by Django 4.0.4 on 2022-05-10 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crecimientoPlanta', '0004_monitoreo_altura_monitoreo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='altura',
            field=models.FloatField(blank=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='plantas',
            name='fecha_siembra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
