# Generated by Django 4.0.4 on 2022-05-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crecimientoPlanta', '0005_alter_monitoreo_altura_alter_plantas_fecha_siembra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoreo',
            old_name='updated_at',
            new_name='timestamp_muestra',
        ),
        migrations.RemoveField(
            model_name='monitoreo',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='plantas',
            name='fecha_siembra',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
