# Generated by Django 4.0.4 on 2022-05-10 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crecimientoPlanta', '0006_rename_updated_at_monitoreo_timestamp_muestra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantas',
            name='fecha_siembra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
