# Generated by Django 4.0.4 on 2022-06-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crecimientoPlanta', '0013_alter_plantas_fecha_siembra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia_Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura_referencia', models.FloatField(default=81.5)),
            ],
            options={
                'verbose_name_plural': 'Referencia de Medicion',
            },
        ),
    ]
