# Generated by Django 4.0.4 on 2022-05-25 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlLuces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion_luces',
            name='hora_apagado',
        ),
        migrations.RemoveField(
            model_name='programacion_luces',
            name='hora_encendido',
        ),
        migrations.RemoveField(
            model_name='programacion_luces',
            name='minuto_apagado',
        ),
        migrations.RemoveField(
            model_name='programacion_luces',
            name='minuto_encendido',
        ),
        migrations.AddField(
            model_name='programacion_luces',
            name='apagado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='programacion_luces',
            name='encendido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
