# Generated by Django 4.0.4 on 2022-05-25 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlLuces', '0002_remove_programacion_luces_hora_apagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion_luces',
            name='apagado',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='programacion_luces',
            name='encendido',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
