# Generated by Django 4.0.4 on 2022-05-26 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlLuces', '0003_alter_programacion_luces_apagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion_luces',
            name='apagado',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='programacion_luces',
            name='encendido',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
