# Generated by Django 4.0.4 on 2022-06-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlLuces', '0007_alter_programacion_luces_hora_apagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion_luces',
            name='hora_apagado',
            field=models.PositiveSmallIntegerField(blank=b'I01\n', choices=[(0, '00'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], default=21, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='programacion_luces',
            name='hora_encendido',
            field=models.PositiveSmallIntegerField(blank=b'I01\n', choices=[(0, '00'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], default=6, null=b'I01\n'),
        ),
    ]
